name             'loop-lvm'
maintainer       'Venkat Venkataraju'
maintainer_email 'venkat.venkataraju@yahoo.com'
license          'MIT'
description      'Installs/Configures loop-lvm'
long_description 'Installs/Configures loop-lvm'
version          '0.1.0'
